// =============================================================================
// TYPES / index.ts
// =============================================================================
// Central TypeScript type definitions for the entire Smart Monitor application.
//
// Data model summary:
//   Equipment  ──owns──►  sensors (Record<SensorKey, SensorReading>)
//                         thresholds (EquipmentThresholdSet)
//                         baseline   (used by sensorSimulator as "normal" target)
//   Alert      ──references──►  Equipment (by id/name)
//   Inspection ──references──►  Equipment (by id/name), contains InspectionCheck[]
//   ActivityEvent  lightweight log entry surfaced in the timeline widget
//   ScenarioTarget  partial sensor target values used by demo scenarios
// =============================================================================

// Possible operational states of a piece of equipment.
export type EquipmentStatus = 'Running' | 'Idle' | 'Maintenance' | 'Warning' | 'Critical';

// The five physical sensors monitored on every piece of equipment.
export type SensorKey = 'temperature' | 'current' | 'voltage' | 'vibration' | 'pressure';

// Severity level assigned to a sensor reading after threshold evaluation.
export type Severity = 'normal' | 'warning' | 'critical';

// One live sensor reading, including its rolling history buffer (last 40 points)
// used by LiveChart and the anomaly engine's rate-of-change calculation.
export interface SensorReading {
  key: SensorKey;
  label: string;
  unit: string;
  value: number;
  history: { t: number; v: number }[];
  severity: Severity;
}

// Warning/critical boundaries for a single sensor.
// Low bounds are optional — only voltage has both high and low limits.
export interface Thresholds {
  warningLow?: number;
  warningHigh: number;
  criticalLow?: number;
  criticalHigh: number;
}

// Full threshold configuration for one piece of equipment (one Thresholds per sensor).
// Copied from DEFAULT_THRESHOLDS at equipment creation so each asset can be tuned independently.
export interface EquipmentThresholdSet {
  temperature: Thresholds;
  current: Thresholds;
  voltage: Thresholds;
  vibration: Thresholds;
  pressure: Thresholds;
}

// The core domain object. One Equipment instance per physical asset.
// `baseline` stores the "healthy normal" sensor value used by the simulator
// as its drift center. `health` and `anomalyScore` are recomputed every tick.
export interface Equipment {
  id: string;
  name: string;
  type: string;
  location: string;
  manufacturer: string;
  model: string;
  installationDate: string;
  status: EquipmentStatus;
  health: number;
  lastInspection: string | null;
  alertCount: number;
  sensors: Record<SensorKey, SensorReading>;
  thresholds: EquipmentThresholdSet;
  anomalyScore: number;
  anomalyMessages: string[];
  baseline: Record<SensorKey, number>;
}

// An actionable alert generated by alertEngine when a sensor crosses a threshold.
// `parameter` can be 'multi' for alerts that cover several sensors at once.
export interface Alert {
  id: string;
  equipmentId: string;
  equipmentName: string;
  parameter: SensorKey | 'multi';
  value: number | null;
  threshold: number | null;
  severity: Severity;
  timestamp: string;
  status: 'Open' | 'Resolved';
  recommendedAction: string;
  message: string;
}

// A single row in the InspectionStepper table — one per sensor plus a 'final' summary row.
export interface InspectionCheck {
  key: SensorKey | 'final';
  label: string;
  result: 'pass' | 'warning' | 'fail' | 'pending';
  value?: number | string;
  threshold?: number | string;
}

// A completed (or in-progress) inspection record stored in MonitoringContext.
// Created by submitInspection() which merges auto-assessment with inspector input.
export interface Inspection {
  id: string;
  equipmentId: string;
  equipmentName: string;
  inspector: string;
  date: string;
  result: 'PASS' | 'WARNING' | 'FAIL';
  criticalIssues: number;
  status: 'Completed' | 'In Progress';
  checks: InspectionCheck[];
  reasons: string[];
  recommendedAction: string;
  findings: string;
  comments: string;
  correctiveAction: string;
}

// A lightweight log entry added to the activity feed on status changes,
// scenario triggers, or inspection completions. Kept to 60 most recent.
export interface ActivityEvent {
  id: string;
  timestamp: string;
  message: string;
  equipmentId?: string;
  severity: Severity;
}

// Named stages of the full hackathon demo sequence (unused at runtime, kept for docs).
export type DemoStage =
  | 'idle'
  | 'normal'
  | 'rising'
  | 'warning'
  | 'critical'
  | 'alert'
  | 'anomaly'
  | 'inspection'
  | 'fail'
  | 'corrective'
  | 'report';

// Partial override values used by SCENARIO_TARGETS in sensorSimulator.
// During a warning/critical demo scenario, present sensors are pulled toward
// these target values instead of their normal baselines.
export interface ScenarioTarget {
  temperature?: number;
  current?: number;
  voltage?: number;
  vibration?: number;
  pressure?: number;
}
